[program:larkode]
command=/home/sc/Workspaces/github/larkode/.venv/bin/python larkode.py
directory=/home/sc/Workspaces/github/larkode
user=sc
umask=077
numprocs=1
autostart=true
autorestart=true
startsecs=10
startretries=3
exitcodes=0
stopsignal=TERM
stopwaitsecs=15
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/home/sc/Workspaces/github/larkode/logs/supervisor.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
environment=PATH="/home/sc/.local/share/pnpm:/home/sc/.nvmd/bin:/home/sc/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",HOME="/home/sc"
